# Generated by Django 4.2.4 on 2023-08-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_album_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofstudent', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=20)),
                ('mark_out_of_100', models.IntegerField()),
            ],
        ),
    ]
