# Generated by Django 4.2.4 on 2023-08-14 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, null=True)),
                ('author_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='auth_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.author'),
        ),
    ]
